// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGTS.Data.Context;

#nullable disable

namespace SGTS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821204058_Agregando configuracion a categorias")]
    partial class Agregandoconfiguracionacategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGTS.Data.Entities.ActividadTicket", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividad"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoActividad")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdActividad");

                    b.HasIndex("IdTicket");

                    b.HasIndex("IdTipoActividad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ActividadesTickets");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Adjunto", b =>
                {
                    b.Property<int>("IdAdjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdjunto"));

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Tamano")
                        .HasColumnType("bigint");

                    b.HasKey("IdAdjunto");

                    b.HasIndex("IdTicket");

                    b.ToTable("Adjuntos");
                });

            modelBuilder.Entity("SGTS.Data.Entities.AsignacionTicket", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDesasignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdTicket");

                    b.ToTable("AsignacionesTickets");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Nombre = "Hardware"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Nombre = "Software"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Nombre = "Redes y Conectividad"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Nombre = "Sistemas Operativos"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Nombre = "Accesos y Credenciales"
                        },
                        new
                        {
                            IdCategoria = 6,
                            Nombre = "Impresoras y Periféricos"
                        },
                        new
                        {
                            IdCategoria = 7,
                            Nombre = "Correo Electrónico"
                        },
                        new
                        {
                            IdCategoria = 8,
                            Nombre = "Aplicaciones Institucionales"
                        },
                        new
                        {
                            IdCategoria = 9,
                            Nombre = "Soporte al Usuario"
                        },
                        new
                        {
                            IdCategoria = 10,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("SGTS.Data.Entities.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<bool>("EsInicial")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdTicket");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            IdEstado = 1,
                            Nombre = "abierto"
                        },
                        new
                        {
                            IdEstado = 2,
                            Nombre = "en-progreso"
                        },
                        new
                        {
                            IdEstado = 3,
                            Nombre = "resuelto"
                        },
                        new
                        {
                            IdEstado = 4,
                            Nombre = "cerrado"
                        });
                });

            modelBuilder.Entity("SGTS.Data.Entities.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridad"));

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrioridad");

                    b.ToTable("Prioridades");

                    b.HasData(
                        new
                        {
                            IdPrioridad = 1,
                            Nivel = 0,
                            Nombre = "baja"
                        },
                        new
                        {
                            IdPrioridad = 2,
                            Nivel = 0,
                            Nombre = "media"
                        },
                        new
                        {
                            IdPrioridad = 3,
                            Nivel = 0,
                            Nombre = "alta"
                        });
                });

            modelBuilder.Entity("SGTS.Data.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "tecnico"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "empleado"
                        },
                        new
                        {
                            IdRol = 4,
                            Nombre = "supervisor"
                        });
                });

            modelBuilder.Entity("SGTS.Data.Entities.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdTicket");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPrioridad");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SGTS.Data.Entities.TipoActividadTicket", b =>
                {
                    b.Property<int>("IdTipoActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoActividad"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoActividad");

                    b.ToTable("TiposActividadTicket");

                    b.HasData(
                        new
                        {
                            IdTipoActividad = 1,
                            Nombre = "creacion"
                        },
                        new
                        {
                            IdTipoActividad = 2,
                            Nombre = "comentario"
                        },
                        new
                        {
                            IdTipoActividad = 3,
                            Nombre = "asignacion"
                        },
                        new
                        {
                            IdTipoActividad = 4,
                            Nombre = "reasignacion"
                        },
                        new
                        {
                            IdTipoActividad = 5,
                            Nombre = "cambio-estado"
                        },
                        new
                        {
                            IdTipoActividad = 6,
                            Nombre = "cambio-prioridad"
                        },
                        new
                        {
                            IdTipoActividad = 7,
                            Nombre = "cambio-categoria"
                        },
                        new
                        {
                            IdTipoActividad = 8,
                            Nombre = "cierre"
                        },
                        new
                        {
                            IdTipoActividad = 9,
                            Nombre = "reapertura"
                        });
                });

            modelBuilder.Entity("SGTS.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGTS.Data.Entities.UsuarioAsignacion", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuariosAsignaciones");
                });

            modelBuilder.Entity("SGTS.Data.Entities.ActividadTicket", b =>
                {
                    b.HasOne("SGTS.Data.Entities.Ticket", "Ticket")
                        .WithMany("Actividades")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.TipoActividadTicket", "TipoActividad")
                        .WithMany("Actividades")
                        .HasForeignKey("IdTipoActividad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.Usuario", "Usuario")
                        .WithMany("ActividadesTickets")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("TipoActividad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Adjunto", b =>
                {
                    b.HasOne("SGTS.Data.Entities.Ticket", "Ticket")
                        .WithMany("Adjuntos")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SGTS.Data.Entities.AsignacionTicket", b =>
                {
                    b.HasOne("SGTS.Data.Entities.Usuario", "Tecnico")
                        .WithMany("AsignacionesTickets")
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.Ticket", "Ticket")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnico");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Comentario", b =>
                {
                    b.HasOne("SGTS.Data.Entities.Ticket", "Ticket")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Ticket", b =>
                {
                    b.HasOne("SGTS.Data.Entities.Categoria", "Categoria")
                        .WithMany("Tickets")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.Estado", "Estado")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.Prioridad", "Prioridad")
                        .WithMany("Tickets")
                        .HasForeignKey("IdPrioridad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.Usuario", "Usuario")
                        .WithMany("TicketsCreados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGTS.Data.Entities.Usuario", null)
                        .WithMany("TicketsAsignados")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Categoria");

                    b.Navigation("Estado");

                    b.Navigation("Prioridad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGTS.Data.Entities.UsuarioAsignacion", b =>
                {
                    b.HasOne("SGTS.Data.Entities.Departamento", "Departamento")
                        .WithMany("UsuarioAsignaciones")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGTS.Data.Entities.Rol", "Rol")
                        .WithMany("UsuarioAsignaciones")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGTS.Data.Entities.Usuario", "Usuario")
                        .WithOne("UsuarioAsignacion")
                        .HasForeignKey("SGTS.Data.Entities.UsuarioAsignacion", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Categoria", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Departamento", b =>
                {
                    b.Navigation("UsuarioAsignaciones");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Estado", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Prioridad", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioAsignaciones");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Ticket", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Adjuntos");

                    b.Navigation("Asignaciones");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("SGTS.Data.Entities.TipoActividadTicket", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("SGTS.Data.Entities.Usuario", b =>
                {
                    b.Navigation("ActividadesTickets");

                    b.Navigation("AsignacionesTickets");

                    b.Navigation("Comentarios");

                    b.Navigation("TicketsAsignados");

                    b.Navigation("TicketsCreados");

                    b.Navigation("UsuarioAsignacion");
                });
#pragma warning restore 612, 618
        }
    }
}
