<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SGTS.Data\SGTS.Data.csproj" />
    <ProjectReference Include="..\SGTS.Models\SGTS.Models.csproj" />
    <ProjectReference Include="..\SGTS.Shared\SGTS.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
